{
 * Identifiers for bitmap resources.
 *
 * $Rev: 21 $
 * $Date: 2013-10-27 15:49:17 +0000 (Sun, 27 Oct 2013) $
 *
 * This file is licensed under the MIT license.
 *
 * Copyright (c) 2013, Peter Johnson, http://delphidabbler.com and
 * http://codedabbler.co.uk
}


const
	IDB_FLAG	    =	 97;
	IDB_QUERY	    =	 98;
	IDB_CLEAR	    =	 99;
	IDB_EMPTY	    =	100;
	IDB_NOTRAP	  =	109;
	IDB_EXPTRAP	  =	110;
	IDB_TRAP	    =	111;
	IDB_FLAGTRAP	=	112;

  FIRST_BMP     =  97;
  LAST_BMP      = 112;

  BMP_OFFSET    =   3;


